config/routes.rb
Rails.application.routes.draw do
  mount Soulmate::Server, :at => "/autoload"
  namespace :api do
    namespace :v1 do
      resources :snippets
    end
  end

  root 'snippets#index'
  get '/search', to: 'snippets#search'
  resources :snippets, except: [:edit, :destroy, :update]
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  validates_length_of :content, maximum: 8192
  validates_presence_of :content
  scope :public_snippets, ->  {where(private: false)}

  after_create :generate_token, if: Proc.new { self.private? }
  after_save :load_into_soulmate
  before_destroy :remove_from_soulmate

  def generate_token
    begin
      self.token = SecureRandom.urlsafe_base64(64, false)
    end while Snippet.exists?(token: token)
    save!
  end

  def self.search(search)
    where("content like ?", "%#{search}%")
  end

  private
    def load_into_soulmate
      loader = Soulmate::Loader.new("snippets")
      loader.add("term" => content, "id" => self.id, "data" => {
                                   "link" => Rails.application.routes.url_helpers.snippet_path(self)
                               })
    end

    def remove_from_soulmate
      loader = Soulmate::Loader.new("snippets")
      loader.remove("id" => self.id)
    end

end

app/controllers/api/v1/snippets_controller.rb
module Api
  module V1
    class SnippetsController < ApplicationController
      skip_before_filter :verify_authenticity_token
      respond_to :json

      def index
        if params[:limit]
          respond_with Snippet.order("id desc").limit(params[:limit])
        else
          respond_with Snippet.all
        end
      end

      def show
        snippet =  Snippet.find(params[:id])
        render(json: snippet)
      end

      def create
        respond_with Snippet.create(snippet_params)
      end

      def update
        respond_with Snippet.update(params[:id], params[:snippets])
      end

      def destroy
        respond_with Snippet.destroy(params[:id])
      end

      private
        def snippet_params
          params.require(:snippet).permit(:content, :private)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  include SnippetsHelper
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]
  before_filter :redirection, only: [:show]

  # GET /snippets
  # GET /snippets.json
  def index
    fetch_snippets
    @count = Snippet.all.count
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        if @snippet.token
          format.html { redirect_to snippet_path(@snippet.token), notice: 'Snippet was successfully created.' }
        else
          format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        end
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @snippets = Snippet.search(params[:search])
  end

  def redirection
    set_snippet
    if @snippet.token? && @param.present?
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @param = Integer(params[:id]) rescue nil
      if @param.nil?
        @snippet = Snippet.find_by_token(params[:id])
      else
        @snippet = Snippet.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:content, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
  def active_snippet?(snippet)
    if snippet["token"]
      raw "<li class='list-group-item'>#{snippet["content"].split[0...15].join(' ')}</li>"
    else
      link_to snippet["content"].split[0...15].join(' '), '#', class: 'list-group-item'
    end
  end

  def snippet_share(snippet)
    if snippet.token?
      text_field_tag :url, snippet_url(snippet.token), class: 'form-control'
    else
      text_field_tag :url, snippet_url(snippet), class: 'form-control'
    end
  end

  def fetch_snippets
    snippets =  $redis.get("snippets")
    if snippets.nil?
      snippets = Snippet.all.to_json
      $redis.set("snippets", snippets)
      # Expire the cache, every 5 hours
      $redis.expire("snippets",5.hour.to_i)
    end
    @snippets = JSON.load snippets
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnippetDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<style type="text/css">
    body{
        padding-top: 60px;
    }
</style>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Snippet', root_path, class: 'navbar-brand' %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

</body>
</html>

app/views/snippets/_form.html.erb
<div>
  <%= form_for(@snippet, class: 'form-inline') do |f| %>
      <% if @snippet.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

            <ul>
              <% @snippet.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.text_area :content, placeholder: 'Your snippet comes here..', class: 'form-control', rows: 7 %>
      </div>

      <div class="form-group">
        Private?<br>
        <%= f.check_box :private %>
        <%= submit_tag 'Save', class: 'btn btn-default pull-right' %>
      </div>
  <% end %>
</div>

app/views/snippets/_snippet.html.erb
<div class="panel panel-default">
  <!-- List group -->
  <ul class="list-group">
    <% for snippet in @snippets %>
        <%= link_to snippet.content.split[0...15].join(' '), snippet, class: 'list-group-item' %>
    <% end %>
  </ul>
</div>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag '', remote: true, class: 'form-inline' do %>
  <div class="form-group">
    <%= text_field_tag :search, nil, placeholder: 'Search', class: 'form-control' %>
  </div>
<% end %>

<div class="snip-header">
  <h1>
    <%= @count %> Snippets
    <%= link_to button_tag('Create Snippet', class: 'btn btn-primary pull-right'), new_snippet_path %>
  </h1>
</div>
<style>
  .snip-header {
      padding-bottom: 20px;
  }
</style>

<div id="snippet">
    <div class="panel panel-default">
      <!-- List group -->
      <ul class="list-group">
        <% for snippet in @snippets %>
          <%= active_snippet?(snippet) %>
        <% end %>
      </ul>
    </div>
</div>

app/views/snippets/new.html.erb
<h1>Create your snippet</h1>

<%= render 'form' %>

app/views/snippets/search.js.erb
$('#snippet').html('<%= escape_javascript(render(:partial => "snippet", :locals => { :snippets => @snippets})) %>');

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @snippet.content.split[0...15].join(' ') %></h3>
  </div>
  <div class="panel-body">
    <%= @snippet.content %>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Share this</h3>
  </div>
  <div class="panel-body">
    <%= snippet_share(@snippet) %>
  </div>
</div>